---
abstract: 'AnyEvent HTTP server for PSGI (like Thin)'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Twiggy
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  EV: 0
  HTTP::Parser::XS: 0
requires:
  AnyEvent: 0
  Filter::Util::Call: 0
  HTTP::Status: 0
  Plack: 0.99
  Try::Tiny: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Twiggy.git
version: 0.1005
