---
abstract: 'AnyEvent HTTP server for PSGI (like Thin)'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  Test::More: '0'
  Test::Requires: '0'
  Test::TCP: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, Dist::Milla version v1.0.9, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Twiggy
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  AnyEvent: '0'
  HTTP::Status: '0'
  Plack: '0.99'
  Try::Tiny: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/miyagawa/Twiggy/issues
  homepage: https://github.com/miyagawa/Twiggy
  repository: https://github.com/miyagawa/Twiggy.git
version: '0.1025'
x_contributors:
  - 'Adam Thomason <ad@mthomason.net>'
  - 'Chia-liang Kao <clkao@clkao.org>'
  - 'Kazuho Oku <kazuho@kazdev.in.labs.cybozu.co.jp>'
  - 'Moritz Onken <onken@netcubed.de>'
  - 'Pedro Melo <melo@simplicidade.org>'
  - 'Rob Hoelz <rob@hoelz.ro>'
  - 'Sergey Zasenko <d3fin3@gmail.com>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
  - 'Tomas Doran (t0m) <t0m@state51.co.uk>'
  - 'Yuval Kogman <nothingmuch@woobling.org>'
  - 'hidekiy <hideki.yamamura@gmail.com>'
  - 'lestrrat <lestrrat+github@gmail.com>'
  - 'maedama <klemensplatz+githhub@gmail.com>'
  - 'moznion <moznion@gmail.com>'
